server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    accesslog:
      pattern: common
      enabled: true
      directory: ../logs
      prefix: jeesite_access_log
      suffix: .log
      request-attributes-enabled: true
      rename-on-rotate: true
logging:
  level:
    root: INFO
    com.baidu.cms: DEBUG
    org.apache.shiro.cache.ehcache.EhCacheManager: WARN
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      base:
        url: jdbc:mysql://10.99.198.188:8411/d_ai_studio_cms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: MhxzKhl
      studio:
        url: jdbc:mysql://10.99.198.188:8411/d_ai_studio?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: MhxzKhl
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  #springMvc的配置
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    servlet:
      load-on-startup: 1
  #spring-ehcache的配置
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
#mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mappings/**/*.xml
  type-aliases-package: com.baidu.cms
#admin页面管理Path
adminPath: /admin
#分页配置
page:
  pageSize: 10
#文件上传的路径
userfiles:
  basedir: /Users/v_shiyanjun/jeesite/upload2